# Работает и на Intel, и на Apple Silicon
FROM eclipse-temurin:17-jre-jammy

WORKDIR /app
COPY 1C_mcp_bsl.jar /app/1C_mcp_bsl.jar

# ENTRYPOINT чтобы STDIO сразу уходил наружу
ENTRYPOINT ["java", "-jar", "/app/1C_mcp_bsl.jar"]

# Дополнительные аргументы (например --platform-path)
# получим из docker run, поэтому CMD не задаём

CMD ["java", "-jar", "/app/1C_mcp_bsl.jar", "--mode", "stdio", "--platform-path", "/app/1c-platform"]
